### ISSUE TITLE
pressing c fail

### ISSUE THREAD

**Issue by zhaobaozi** [EvilPort2/Simple-OpenCV-Calculator#1]
when the set hand histogram appear,i put my hand in the sqare,but always failed...what can i do?thanks

**Comment by Liangbo5060** [comment]
The following error occurred while running ‘hand-calculator’:
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "hand-calculator.py", line 181, in <module>
    start_calculator()
  File "hand-calculator.py", line 83, in start_calculator
    imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
Thank you
